// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0mzEbHnoEmU2_H_1buPU2xF9qB6rdpTU',
    appId: '1:1018311673704:web:bd3cf6928a1436e5b1f8dd',
    messagingSenderId: '1018311673704',
    projectId: 'travel-app-8545f',
    authDomain: 'travel-app-8545f.firebaseapp.com',
    storageBucket: 'travel-app-8545f.appspot.com',
    measurementId: 'G-VL8KPGR373',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8k7fMZiIVdZwqMV27by0w7s1UMBTmQ68',
    appId: '1:1018311673704:android:453d5e6c9999be9fb1f8dd',
    messagingSenderId: '1018311673704',
    projectId: 'travel-app-8545f',
    storageBucket: 'travel-app-8545f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mByyLqrUY46jnJ5D6X55tZ4iS2uYrNY',
    appId: '1:1018311673704:ios:a13f84b2d722dc30b1f8dd',
    messagingSenderId: '1018311673704',
    projectId: 'travel-app-8545f',
    storageBucket: 'travel-app-8545f.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mByyLqrUY46jnJ5D6X55tZ4iS2uYrNY',
    appId: '1:1018311673704:ios:a13f84b2d722dc30b1f8dd',
    messagingSenderId: '1018311673704',
    projectId: 'travel-app-8545f',
    storageBucket: 'travel-app-8545f.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0mzEbHnoEmU2_H_1buPU2xF9qB6rdpTU',
    appId: '1:1018311673704:web:fe49217719266561b1f8dd',
    messagingSenderId: '1018311673704',
    projectId: 'travel-app-8545f',
    authDomain: 'travel-app-8545f.firebaseapp.com',
    storageBucket: 'travel-app-8545f.appspot.com',
    measurementId: 'G-XVM66W4TRS',
  );
}
